# Cloud Build configuration for Google Cloud Run deployment
steps:
  # Build the Docker image with build arguments and layer caching
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--cache-from'
      - 'gcr.io/$PROJECT_ID/omi-ai:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/omi-ai:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/omi-ai:$BUILD_ID'
      - '.'
    timeout: 1800s

  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/omi-ai:latest'

# Timeout for the entire build
timeout: 2400s

# Save the built image
images:
  - 'gcr.io/$PROJECT_ID/omi-ai:latest'
  - 'gcr.io/$PROJECT_ID/omi-ai:$BUILD_ID'

# Use more powerful machine for faster builds
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
