/**
 * Video Poster Mapping Utility
 *
 * Maps video URLs to their poster images for lazy loading optimization.
 * Posters are generated using scripts/generate-video-posters.mjs
 */

// Static mapping of video files to their poster images
// This is populated after running the poster generation script
// Format: { '/videos/example.mp4': '/videos/posters/example.jpg' }
const posterMap: Record<string, string> = {
  // Hero/Featured videos - these should have posters for best UX
  '/videos/film.mp4': '/videos/posters/film.jpg',
  '/videos/veo-hero.mp4': '/videos/posters/veo-hero.jpg',
  '/videos/intro.mp4': '/videos/posters/intro.jpg',
  '/videos/ray3darkspace.mp4': '/videos/posters/ray3darkspace.jpg',
  '/videos/matrixcode.mp4': '/videos/posters/matrixcode.jpg',

  // Add more mappings as posters are generated
  // These will be auto-generated by the script
};

/**
 * Get the poster URL for a video
 * Returns undefined if no poster is available
 */
export function getVideoPoster(videoSrc: string): string | undefined {
  // Normalize the path
  const normalizedPath = videoSrc.startsWith('http')
    ? new URL(videoSrc).pathname
    : videoSrc;

  // Check if we have a pre-generated poster
  if (posterMap[normalizedPath]) {
    return posterMap[normalizedPath];
  }

  // Try to construct a poster path (assumes posters follow naming convention)
  const posterPath = normalizedPath
    .replace(/\.(mp4|webm|mov)$/i, '.jpg')
    .replace('/videos/', '/videos/posters/');

  // Return undefined to let the component handle it
  // In production, you might want to check if the file exists server-side
  return undefined;
}

/**
 * Generate a low-quality placeholder image URL
 * Uses a data URL for instant loading
 */
export function getPlaceholderDataUrl(
  width: number = 16,
  height: number = 9,
  color: string = '#1a1a1a'
): string {
  // Create a simple SVG placeholder
  const svg = `
    <svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">
      <rect width="100%" height="100%" fill="${color}"/>
    </svg>
  `.trim();

  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

/**
 * Common video poster configurations
 */
export const videoPosterConfig = {
  // Aspect ratios
  aspectRatios: {
    '16:9': 'aspect-video',
    '4:3': 'aspect-[4/3]',
    '1:1': 'aspect-square',
    '9:16': 'aspect-[9/16]',
    '3:4': 'aspect-[3/4]',
  },

  // Default placeholder colors matching the UI theme
  placeholderColors: {
    dark: '#0a0a0a',
    neutral: '#1a1a1a',
    accent: '#1e1e2e',
  },

  // Intersection observer defaults optimized for performance
  observerDefaults: {
    threshold: 0.1, // 10% visible triggers load
    rootMargin: '200px', // Start loading 200px before visible
  },
} as const;

export default getVideoPoster;
